name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-client:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          os: ubuntu-latest
          cmake-args: -G Ninja
          package-file: "*-linux_x86_64.tar.xz"
        - name: macOS
          os: macOS-latest
          cmake-args: -G Ninja
          package-file: "*-macos.dmg"
        - name: Windows
          os: windows-latest
          cmake-args: -A x64 -DVULKAN=ON
          package-file: "*-win64.zip"

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Prepare Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          libavcodec-dev \
          libavformat-dev \
          libavutil-dev \
          libfreetype6-dev \
          libglew-dev \
          libnotify-dev \
          libpng-dev \
          libsdl2-dev \
          libsqlite3-dev \
          libswresample-dev \
          libswscale-dev \
          libx264-dev \
          ninja-build \
          pkg-config

    - name: Prepare macOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install ffmpeg molten-vk ninja pkg-config sdl2
        pip3 install --break-system-packages dmgbuild pyobjc-framework-Quartz
        echo /Library/Frameworks/Python.framework/Versions/3.12/bin >> $GITHUB_PATH
        sudo rm -rf /Library/Developer/CommandLineTools

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.3.296.0
        cache: true

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2.9.2

    - name: Build and package client
      run: |
        mkdir build
        cd build
        cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release -DSERVER=OFF -DTOOLS=OFF ..
        cmake --build . --config Release --target package_default

    - name: Collect package
      shell: bash
      run: |
        mkdir artifacts
        mv build/${{ matrix.package-file }} artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v6
      with:
        name: ddnet-${{ matrix.name }}
        path: artifacts
        if-no-files-found: error

    - name: Upload to release
      if: github.event_name == 'release'
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release upload "${{ github.event.release.tag_name }}" artifacts/* --clobber --repo "${{ github.repository }}"
